name: pretty_animated_buttons
description: A collection of fancy animated buttons package
version: 0.0.1
repository: https://github.com/YeLwinOo-Steve/pretty_animated_buttons
homepage: https://github.com/YeLwinOo-Steve/pretty_animated_buttons

environment:
  sdk: ">=3.5.3 <4.0.0"
  flutter: ">=3.27.2"

dependencies:
  flutter:
    sdk: flutter
  flutter_inset_box_shadow: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
